# We need to pin here to the same clang version as abseil currently uses to avoid linkage errors.
c_compiler:
  - clang
c_compiler_version:
  - 17
cxx_compiler:
  - clangxx
cxx_compiler_version:
  - 17
